/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ManifoldButton {
    'href': string;
  }
  interface ManifoldCheckbox {
    'checked': boolean;
    'inputId': string;
    'name': string;
  }
  interface ManifoldPlanMatrix {
    'baseUrl'?: string;
    'ctaText'?: string;
  }
}

declare global {


  interface HTMLManifoldButtonElement extends Components.ManifoldButton, HTMLStencilElement {}
  var HTMLManifoldButtonElement: {
    prototype: HTMLManifoldButtonElement;
    new (): HTMLManifoldButtonElement;
  };

  interface HTMLManifoldCheckboxElement extends Components.ManifoldCheckbox, HTMLStencilElement {}
  var HTMLManifoldCheckboxElement: {
    prototype: HTMLManifoldCheckboxElement;
    new (): HTMLManifoldCheckboxElement;
  };

  interface HTMLManifoldPlanMatrixElement extends Components.ManifoldPlanMatrix, HTMLStencilElement {}
  var HTMLManifoldPlanMatrixElement: {
    prototype: HTMLManifoldPlanMatrixElement;
    new (): HTMLManifoldPlanMatrixElement;
  };
  interface HTMLElementTagNameMap {
    'manifold-button': HTMLManifoldButtonElement;
    'manifold-checkbox': HTMLManifoldCheckboxElement;
    'manifold-plan-matrix': HTMLManifoldPlanMatrixElement;
  }
}

declare namespace LocalJSX {
  interface ManifoldButton {
    'href'?: string;
  }
  interface ManifoldCheckbox {
    'checked'?: boolean;
    'inputId'?: string;
    'name'?: string;
  }
  interface ManifoldPlanMatrix {
    'baseUrl'?: string;
    'ctaText'?: string;
  }

  interface IntrinsicElements {
    'manifold-button': ManifoldButton;
    'manifold-checkbox': ManifoldCheckbox;
    'manifold-plan-matrix': ManifoldPlanMatrix;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'manifold-button': LocalJSX.ManifoldButton & JSXBase.HTMLAttributes<HTMLManifoldButtonElement>;
      'manifold-checkbox': LocalJSX.ManifoldCheckbox & JSXBase.HTMLAttributes<HTMLManifoldCheckboxElement>;
      'manifold-plan-matrix': LocalJSX.ManifoldPlanMatrix & JSXBase.HTMLAttributes<HTMLManifoldPlanMatrixElement>;
    }
  }
}


