/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  PlanEdge,
} from 'types/graphql';

export namespace Components {
  interface ManifoldButton {
    'href': string;
    'text': string;
  }
  interface ManifoldCheckbox {
    'checked': boolean;
    'inputId': string;
    'name': string;
  }
  interface ManifoldPlanMatrix {
    'actionUrl': string;
    'productLabel': string;
  }
  interface ManifoldThead {
    'plan'?: PlanEdge;
    'titleText': string;
  }
}

declare global {


  interface HTMLManifoldButtonElement extends Components.ManifoldButton, HTMLStencilElement {}
  var HTMLManifoldButtonElement: {
    prototype: HTMLManifoldButtonElement;
    new (): HTMLManifoldButtonElement;
  };

  interface HTMLManifoldCheckboxElement extends Components.ManifoldCheckbox, HTMLStencilElement {}
  var HTMLManifoldCheckboxElement: {
    prototype: HTMLManifoldCheckboxElement;
    new (): HTMLManifoldCheckboxElement;
  };

  interface HTMLManifoldPlanMatrixElement extends Components.ManifoldPlanMatrix, HTMLStencilElement {}
  var HTMLManifoldPlanMatrixElement: {
    prototype: HTMLManifoldPlanMatrixElement;
    new (): HTMLManifoldPlanMatrixElement;
  };

  interface HTMLManifoldTheadElement extends Components.ManifoldThead, HTMLStencilElement {}
  var HTMLManifoldTheadElement: {
    prototype: HTMLManifoldTheadElement;
    new (): HTMLManifoldTheadElement;
  };
  interface HTMLElementTagNameMap {
    'manifold-button': HTMLManifoldButtonElement;
    'manifold-checkbox': HTMLManifoldCheckboxElement;
    'manifold-plan-matrix': HTMLManifoldPlanMatrixElement;
    'manifold-thead': HTMLManifoldTheadElement;
  }
}

declare namespace LocalJSX {
  interface ManifoldButton {
    'href'?: string;
    'text'?: string;
  }
  interface ManifoldCheckbox {
    'checked'?: boolean;
    'inputId'?: string;
    'name'?: string;
  }
  interface ManifoldPlanMatrix {
    'actionUrl'?: string;
    'productLabel'?: string;
  }
  interface ManifoldThead {
    'plan'?: PlanEdge;
    'titleText'?: string;
  }

  interface IntrinsicElements {
    'manifold-button': ManifoldButton;
    'manifold-checkbox': ManifoldCheckbox;
    'manifold-plan-matrix': ManifoldPlanMatrix;
    'manifold-thead': ManifoldThead;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'manifold-button': LocalJSX.ManifoldButton & JSXBase.HTMLAttributes<HTMLManifoldButtonElement>;
      'manifold-checkbox': LocalJSX.ManifoldCheckbox & JSXBase.HTMLAttributes<HTMLManifoldCheckboxElement>;
      'manifold-plan-matrix': LocalJSX.ManifoldPlanMatrix & JSXBase.HTMLAttributes<HTMLManifoldPlanMatrixElement>;
      'manifold-thead': LocalJSX.ManifoldThead & JSXBase.HTMLAttributes<HTMLManifoldTheadElement>;
    }
  }
}


